### ISSUE TITLE
C++ interop

### ISSUE THREAD

**Issue by Laeeth** [timotheecour/D_vs_nim#31] opened 2019-07-06 14:15 UTC
I guess you should mention extern(C++).  You can use dpp to #include C++ headers if you blacklist STL and Boost types and it will work for quite a lot.  It's still not complete yet but it keeps getting better and in a year or two STL should be fine.  It's used in production but it's not something I would say is easy for just anyone to use and expect to work immediately.  For C++ - C mostly just works. 

Can you do that now using Nim?  Just include c++ headers and use them?

How about generating c++ headers from Nim code?  We do that in D but the available options aren't yet polished.

**Comment by timotheecour** [comment] 2019-07-10 23:33
duplicate of https://github.com/timotheecour/D_vs_nim/issues/12 ; but see my answer here: https://github.com/timotheecour/D_vs_nim/issues/12#issuecomment-510277885 we can follow up there

**Closed as completed** 2019-07-11 00:22 UTC
